name: Build and Release

env:
  PROJECT_NAME: PredictiveKeyboard

on:
  push:
    branches:
      - main

jobs:
  build_and_release:
    name: Build and Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install dotnet core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '6.0.x'
          include-prerelease: true

      - name: Install WASM tools
        run: dotnet workload install wasm-tools

      - name: Run tests
        run: dotnet test

      - name: Generate pretrained models
        run: dotnet run --project ./Utils/Utils.csproj --generatemodels

      - name: Build web
        run: dotnet publish Web/Web.csproj -c Release -o release

      # changes the base-tag in index.html from '/' to 'PredictiveKeyboard' to match GitHub Pages repository subdirectory
      - name: Change base-tag in index.html from / to PredictiveKeyboard
        run: sed -i 's/<base href="\/" \/>/<base href="\/PredictiveKeyboard\/" \/>/g' release/wwwroot/index.html


      # copy index.html to 404.html to serve the same file when a file is not found
      - name: copy index.html to 404.html
        run: cp release/net6.0/publish/wwwroot/index.html release/net6.0/publish/wwwroot/404.html

      # add .nojekyll file to tell GitHub pages to not treat this as a Jekyll project. (Allow files and folders starting with an underscore)
      - name: Add .nojekyll file
        run: touch release/net6.0/publish/wwwroot/.nojekyll

      - name: GitHub Pages
        uses: crazy-max/ghaction-github-pages@v2.5.0
        with:
          target_branch: gh-pages
          build_dir: Web/bin/Release/net6.0/publish/wwwroot
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
